---
- hosts: all
  vars:
    # the following variables are passed via Ansible Tower type credential from Tower server
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_verify_ssl: "{{ lookup('env', 'TOWER_VERIFY_SSL') }}"
    # fail if remaining license count falls below this threshold
    threshold: 10

  tasks:
    # - debug:
    #     msg: "{{ tower_verify_ssl }}"

    - name: retrieve license info from Tower
      uri:
        url: "https://{{ tower_host }}/api/v2/settings/all/"
        url_username: "{{ tower_username }}"
        url_password: "{{ tower_password }}"
        validate_certs: "{{ tower_verify_ssl }}"
        force_basic_auth: yes
        method: 'GET'
        body_format: 'json'
      register: settings

    - name: retrieve hosts in all inventories from Tower
      uri:
        url: "https://{{ tower_host }}/api/v2/hosts/"
        url_username: "{{ tower_username }}"
        url_password: "{{ tower_password }}"
        validate_certs: "{{ tower_verify_ssl }}"
        force_basic_auth: yes
        method: 'GET'
        body_format: 'json'
      register: hosts

    - set_fact:
        max: "{{ settings.json.LICENSE.instance_count }}"
        used: "{{ hosts.json.count }}"

    - set_fact:
        remaining: "{{ max|int - used|int }}"

    - debug:
        msg: "Valid={{ max }} / Used={{ used }} / Remaining={{ remaining }} / Threshold={{ threshold }}"

    - debug:
        msg: "There are still plenty of licenses remaining to be used"
      when: remaining|int >= threshold

    - debug:
        msg: "Running out of licenses"
      when: remaining|int < threshold

    - name: fail if remaining < threshold
      fail:
        msg: "Running out of licenses"
      when: remaining|int < threshold
