---
- hosts: all
  vars:
    # the following variables are passed via Ansible Tower type credential from Tower server
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_verify_ssl: "{{ lookup('env', 'TOWER_VERIFY_SSL') | default(false) }}"
    # fail if remaining license count falls below this threshold
    threshold: 10

  tasks:
    # - debug:
    #     msg: "{{ tower_verify_ssl }}"

    - name: retrieve license info from Tower
      uri:
        url: "https://{{ tower_host }}/api/v2/settings/all/"
        url_username: "{{ tower_username }}"
        url_password: "{{ tower_password }}"
        validate_certs: "{{ tower_verify_ssl }}"
        force_basic_auth: yes
        method: 'GET'
        body_format: 'json'
      register: settings

    - name: retrieve hosts in all inventories from Tower
      uri:
        url: "https://{{ tower_host }}/api/v2/hosts/"
        url_username: "{{ tower_username }}"
        url_password: "{{ tower_password }}"
        validate_certs: "{{ tower_verify_ssl }}"
        force_basic_auth: yes
        method: 'GET'
        body_format: 'json'
      register: hosts

    # - debug:
    #     var: settings

    # - debug:
    #     var: hosts

    - set_fact:
        max: "{{ settings.json.LICENSE.instance_count }}"
        used: "{{ hosts.json.count }}"

    - debug:
        msg: "There are still {{ max|int - used|int }} licenses remaining to be used: Valid licenses = {{ max }} / Used licenses = {{ used }}"
      when: ((max|int) - (used|int)) >= (threshold|int)

    - debug:
        msg: "Running out of licenses: Valid licenses = {{ max }} / Used licenses = {{ used }}"
      when: ((max|int) - (used|int)) < (threshold|int)

    - name: compare and fail if remaining license count falls below the threshold
      fail:
        msg: "Running out of licenses: Valid licenses = {{ max }} / Used licenses = {{ used }}"
      when: ((max|int) - (used|int)) < (threshold|int)
